#Prompt
# source $XDG_CONFIG_HOME/bash/bash_prompt.sh


# Alias definitions.
if [ -f $XDG_CONFIG_HOME/bash/alias.sh ]; then
    source $XDG_CONFIG_HOME/bash/alias.sh
fi

# zoxide
if [ -f XDG_BIN/zoxide ]; then
    eval "$(zoxide init bash)"
fi


#fzf config
if [ -f $XDG_CONFIG_HOME/fzf/fzf.bash ]; then
    source $XDG_CONFIG_HOME/fzf/fzf.bash
fi



